### ISSUE TITLE
could not access file "login_hook.so" on windows / MSYS

### ISSUE THREAD

**Issue by legrandlegrand** [splendiddata/login_hook#1]
Hello,

after building login_hook extension,  I get

postgres=# create extension login_hook;
ERROR:  could not access file "login_hook.so": No such file or directory

I had to replace 'login_hook.so' by 'login_hook'
in file login_hook--1.0.sql
for C functions definition

this should had been 'MODULE_PATHNAME' but it didn't seem to work.

Regards
PAscal

**Comment by M-Butter** [comment]
Thank you for your remarks and sorry for my horribly late reaction. I'm fairly new at Github and didn't notice your issue before I started working on Postgres 13.

I am afraid I cannot help you on  this. In the entire building over here there is not one Windows machine on which I could test this.

Regards, Martin.

**Comment by legrandlegrand** [comment]
Thank you for the answer.

I had a new look at this, and tested with :
login_hook.control: replacing 
module_pathname = '$libdir/login_hook.so'
with
module_pathname = '$libdir/login_hook'

and 
login_hook--1.0.sql; replacing 2 occurences of
... as 'login_hook.so', ...
with
... as 'MODULE_PATHNAME', ...

and it works fine on windows with MSYS2.

I didn't had the opportunity to test it on linux, but it should work 
(as it is the syntax used in other contrib modules like pg_stat_statements)

Regards
PAscal

**Comment by M-Butter** [comment]
The .so extension appears unnecessary in Linux as well, so I removed it.
