### ISSUE TITLE
Extension version number is not the same as returned version from functionlogin_hook.get_login_hook_version()

### ISSUE THREAD

**Issue by epolkerman** [splendiddata/login_hook#13]
Compiled and installed login_hook extension as described
With psql:

postgres=# \dx
                                   List of installed extensions
    Name    | Version |   Schema   |                          Description                          
------------+---------+------------+---------------------------------------------------------------
 login_hook | 1.2     | login_hook | login_hook - hook to execute login_hook.login() at login time
 plpgsql    | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

postgres=# 
postgres=# 
postgres=# select login_hook.get_login_hook_version();
 get_login_hook_version 
------------------------
 1.3
(1 row)

There is a discrepancy between the version number of login_hok extension reported by \dx and the version reported by the get_login_hook_version() function.

**Comment by M-Butter** [comment]
The default_version in the control file still pointed to version 1.2. That is corrected now to 1.3
