### ISSUE TITLE
cannot execute SQL without an outer snapshot or portal

### ISSUE THREAD

**Issue by oragres** [splendiddata/login_hook#14]
Hi,

i recently updates our postgres cluster from 13.3 to 13.5, after that he login_hook function stopped working.
Whenever i tried to login i got the following message:

gs3-pgres-prd01:/opt/postgresql/13/data3/log [pgd13]$ psql
WARNING:  Function login_hook.login() returned with error in database postgres.
Please resolve the error as only superusers can login now.
HINT:  original message = cannot execute SQL without an outer snapshot or portal
psql (13.5)
Type "help" for help.

i increased the login parameters and tried to see anything in the logs which were causing an issue but couldnt see any.

2021-12-10 09:27:11.498 CET [110808] LOG:  connection received: host=[local]
2021-12-10 09:27:11.499 CET [110808] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2021-12-10 09:27:11.501 CET [110808] WARNING:  Function login_hook.login() returned with error in database postgres.
        Please resolve the error as only superusers can login now.
2021-12-10 09:27:11.501 CET [110808] HINT:  original message = cannot execute SQL without an outer snapshot or portal
2021-12-10 09:27:11.501 CET [110808] DEBUG:  loaded library "login_hook"
2021-12-10 09:27:11.527 CET [110808] LOG:  statement: select substring(''||13.5, 1, position('.' in ''||13.5)-1) as pgreleasenum
2021-12-10 09:27:11.527 CET [110808] LOG:  duration: 0.821 ms
2021-12-10 09:27:13.294 CET [110808] LOG:  disconnection: session time: 0:00:01.797 user=postgres database=postgres host=[local]

I replaced the login_hook.login() function with the default one mentioned here on github:
CREATE OR REPLACE FUNCTION login_hook.login() RETURNS VOID LANGUAGE PLPGSQL AS $$
DECLARE
    ex_state   TEXT;
    ex_message TEXT;
    ex_detail  TEXT;
    ex_hint    TEXT;
    ex_context TEXT;
BEGIN
	IF NOT login_hook.is_executing_login_hook()
	THEN
	    RAISE EXCEPTION 'The login_hook.login() function should only be invoked by the login_hook code';
	END IF;
	
	BEGIN
	   -- 
	   -- Do whatever you need to do at login here.
	   -- For example:
	   RAISE NOTICE 'Hello %', current_user;
	EXCEPTION
	   WHEN OTHERS THEN
	       GET STACKED DIAGNOSTICS ex_state   = RETURNED_SQLSTATE
	                             , ex_message = MESSAGE_TEXT
	                             , ex_detail  = PG_EXCEPTION_DETAIL
	                             , ex_hint    = PG_EXCEPTION_HINT
	                             , ex_context = PG_EXCEPTION_CONTEXT;
	       RAISE LOG e'Error in login_hook.login()\nsqlstate: %\nmessage : %\ndetail  : %\nhint    : %\ncontext : %'
	               , ex_state
	               , ex_message
	               , ex_detail
	               , ex_hint
	               , ex_context;
    END	;       
END 
$$;
GRANT EXECUTE ON FUNCTION login_hook.login() TO PUBLIC;

but i just got the exact same message. I cant find the problem.
The only solution to get non super users to be able to connect again is to delete the login_hook.login() function.
Hope someone can help me with this.

**Comment by M-Butter** [comment]
Hello,

This issue should have been solved with the corrections due to issue https://github.com/splendiddata/login_hook/issues/12. Please check out the latest version and try again.

Regards,
Martin.
