### ISSUE TITLE
Make password available 

### ISSUE THREAD

**Issue by mgogala** [splendiddata/login_hook#15]
Would it be possible to make password available to login_hook.login function? That would make it possible to enforce password complexity rules.
Regards

**Comment by M-Butter** [comment]
The login_hook.login function is executed AFTER the use has logged in, as session_preload_library, so will not be of very much help. And if it could, it would only see the MD5 or SCAM schecksum of the password, which doesn't say very much about the complexity of the original password.

Maybe you would want to have a look at [https://www.postgresql.org/docs/current/passwordcheck.html](https://www.postgresql.org/docs/current/passwordcheck.html). I think that would do the trick.
