### ISSUE TITLE
Application_name is not filled when login() function is load , only in some cases

### ISSUE THREAD

**Issue by edougf** [splendiddata/login_hook#16]
I used the login_hook to record the logons in the database. My problem is that not all data is available when login_hook.login() is called, for example the **"application_name"**, when the connections are via **jdbc**, normally I don't have the application_name, just after the session is already effective.
After the session is already effective, the name of the application already appears normally. Either by current_setting('application_name') or in "SELECT * FROM pg_settings where name like '%application_name%';".
This happens when I establish the connection by **DBeaver**, or by **SQuirreL**. Already by **pgadmin** and local connections, with **psql** , I don't have this problem

On this code (just to exemplify): 
  CREATE OR REPLACE FUNCTION login_hook.login()
   RETURNS void
   LANGUAGE plpgsql
  AS $function$
  DECLARE
   
  BEGIN
        IF NOT login_hook.is_executing_login_hook()
        THEN
            RAISE EXCEPTION 'The login_hook.login() function should only be invoked by the login_hook code';
        END IF;
       
       declare 
       
       vCurrent_user text:=current_user;
       vCurrent_DB text :=current_database();
       vapplication_name text;
       insert_statement text;
       
        BEGIN
			select application_name
				into vapplication_name
			from pg_stat_activity where pid = pg_backend_pid();
			   
			insert_statement = 'INSERT INTO myschema.audit_log
				(login, app,  db_name )
				VALUES(''' || vCurrent_user || ''', ''' 
				|| vapplication_name  || ''', ''' 
				|| vCurrent_DB || ''');';
							
			execute insert_statement;

      END ;
  END
  $function$
  ;	

variable **vapplication_name**  always comes up blank/empty when bindings are via jdbc, but then, if I see it in pg_stat_activity, the application_name is already normal

**Comment by M-Butter** [comment]
In Postgres every session has a process of its own. During process start, in the session_preload_libraries phase, the login_hook.login() function will be executed. This is before the client can have done anything. So the client cannot have set its application name at that point in time.
I'm afraid that if you want a function to be executed during the logon phase, but after client interaction with the database, you will need another trick. Login_hook will not work for you.

**Comment by edougf** [comment]
Hi, 
yes, I noticed that, but why when the call comes from PGADMIN (web admin tool), for example, does it have all the data, including the application_name? 
Wouldn't that be the case for a possible optimization and improvement in login_hook?
I was able to work around the problem using the "options" resource and forcing the application_name set:

jdbc connection: 
jdbc:postgresql://myserver:5432/mydb?ApplicationName=DBeaver&&options=-c%20application_name=DBeaver

without using the "options" the login_hook always received the empty application_name
