### ISSUE TITLE
Does not work after upgrading to version 16

### ISSUE THREAD

**Issue by edougf** [splendiddata/login_hook#18]
Hi, 

After upgrade postgresql from v12 to v16, login hook has different behavior, 
for example: 

v12 , on login_hook.login function : 
      select count(*) into vcount from pg_stat_activity where pid = pg_backend_pid();    -- return "1" , ok my session pid on pg_stat_activity

v16 , on login_hook.login function : 
      select count(*) into vcount from pg_stat_activity where pid = pg_backend_pid();    -- return "0" , does not exist my session pid on pg_stat_activity

when print pg_backend_pid() , value its "ok", but on 16 , not exists on pg_stat_activity

ah, login_hook 1.4 , not work on PG16, i need to use 1.5 last update.

why?????

**Comment by M-Butter** [comment]
Hi,

It looks like pg_stats_activity does not have an entry (yet?) for the starting process in Postgres 16.

I created a little test function as:

> create or replace function login_hook.login() returns void language plpgsql as $$
> begin
> &nbsp;&nbsp;&nbsp;&nbsp;create temp table test_login_hook as select * from pg_stat_activity;
> end
> $$

Then I logged in and executed:

> select pg_backend_pid();
> select * from test_login_hook;

The test_login_hook temp table appeared not to have an entry for my pid.

Then I tested the older postgres versions:
Postgres 12, 13 and 14 did have a pg_stat_activity entry for the pid returned by pg_backend_pid().
Postgres 15 and 16 did not have an entry for pg_backend_pid().

Apparently the Postgres developers decided to create a pg_stat_activity entry after execution of the session_preload_libraries phase in the startup sequence of a Postgres process. I'm afraid I cannot do much about that.

Regards,
Martin.
