### ISSUE TITLE
More of a Database Connection, than Login, Hook?

### ISSUE THREAD

**Issue by bj-github** [splendiddata/login_hook#2]
It seems this also fires each time I switch to a different database after logging in, so perhaps a change in the documentation would be helpful?

Seems to also work well on Postgresql 12 (as packaged in Debian Testing, and running on a RPi4). Having the C piece so I could just focus on the pl/pgsql part was exactly what I needed, thank you very much.

**Comment by M-Butter** [comment]
Thanks for your comment. Sorry for my late reaction. I'm fairly new at Github and only noticed your issue when I started working on Postgres 13.

I slightly altered the documentation and hope this is helpful.
