### ISSUE TITLE
PostgreSQL 17 support

### ISSUE THREAD

**Issue by devrimgunduz** [splendiddata/login_hook#20]
Hi,

PostgreSQL 17 Beta1 is out. and login_hook fails to build against it. Logs are below. Can you please take a look? Thanks! Devrim

> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -fvisibility=hidden -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include  -c -o login_hook.o login_hook.c
> /usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-format-truncation -O2  -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include -flto=thin -emit-llvm -c -o login_hook.bc login_hook.c
> login_hook.c:78:32: error: use of undeclared identifier 'IsBackgroundWorker'
>    78 |              MyProcPid, MyDatabaseId, IsBackgroundWorker, isExecutingLogin, version);
>       |                     gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -fvisibility=hidden -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include  -c -o login_hook.o login_hook.c
/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-format-truncation -O2  -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include -flto=thin -emit-llvm -c -o login_hook.bc login_hook.c
login_hook.c:78:32: error: use of undeclared identifier 'IsBackgroundWorker'
   78 |              MyProcPid, MyDatabaseId, IsBackgroundWorker, isExecutingLogin, version);
      |                                       ^
login_hook.c:106:6: error: use of undeclared identifier 'IsBackgroundWorker'
  106 |         if (IsBackgroundWorker)
      |             ^
2 errors generated.
make[1]: *** [/usr/pgsql-17/lib/pgxs/src/makefiles/../../src/Makefile.global:1085: login_hook.bc] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /usr/pgsql-17/include/server/postgres.h:46,
                 from login_hook.c:18:
login_hook.c: In function ‘_PG_init’:
login_hook.c:78:39: error: ‘IsBackgroundWorker’ undeclared (first use in this function); did you mean ‘BackgroundWorkerLock’?
   78 |              MyProcPid, MyDatabaseId, IsBackgroundWorker, isExecutingLogin, version);
      |                                       ^~~~~~~~~~~~~~~~~~
/usr/pgsql-17/include/server/utils/elog.h:147:25: note: in definition of macro ‘ereport_domain’
  147 |                         __VA_ARGS__, errfinish(__FILE__, __LINE__, __func__); \
      |                         ^~~~~~~~~~~
/usr/pgsql-17/include/server/utils/elog.h:239:9: note: in expansion of macro ‘ereport’
  239 |         ereport(elevel, errmsg_internal(__VA_ARGS__))
      |         ^~~~~~~
login_hook.c:76:9: note: in expansion of macro ‘elog’
   76 |         elog(DEBUG3,
      |         ^~~~
login_hook.c:78:39: note: each undeclared identifier is reported only once for each function it appears in
   78 |              MyProcPid, MyDatabaseId, IsBackgroundWorker, isExecutingLogin, version);
      |                                       ^~~~~~~~~~~~~~~~~~
/usr/pgsql-17/include/server/utils/elog.h:147:25: note: in definition of macro ‘ereport_domain’
  147 |                         __VA_ARGS__, errfinish(__FILE__, __LINE__, __func__); \
      |                         ^~~~~~~~~~~
/usr/pgsql-17/include/server/utils/elog.h:239:9: note: in expansion of macro ‘ereport’
  239 |         ereport(elevel, errmsg_internal(__VA_ARGS__))
      |         ^~~~~~~
login_hook.c:76:9: note: in expansion of macro ‘elog’
   76 |         elog(DEBUG3,
      |         ^~~~
/usr/pgsql-17/include/server/utils/elog.h:147:36: warning: left-hand operand of comma expression has no effect [-Wunused-value]
  147 |                         __VA_ARGS__, errfinish(__FILE__, __LINE__, __func__); \
      |                                    ^
/usr/pgsql-17/include/server/utils/elog.h:164:9: note: in expansion of macro ‘ereport_domain’
  164 |         ereport_domain(elevel, TEXTDOMAIN, __VA_ARGS__)
      |         ^~~~~~~~~~~~~~
/usr/pgsql-17/include/server/utils/elog.h:239:9: note: in expansion of macro ‘ereport’
  239 |         ereport(elevel, errmsg_internal(__VA_ARGS__))
      |         ^~~~~~~
login_hook.c:76:9: note: in expansion of macro ‘elog’
   76 |         elog(DEBUG3,
      |         ^~~~
make[1]: *** [<builtin>: login_hook.o] Error 1
                  ^
> login_hook.c:106:6: error: use of undeclared identifier 'IsBackgroundWorker'
>   106 |         if (IsBackgroundWorker)
>       |             ^
> 2 errors generated.
> make[1]: *** [/usr/pgsql-17/lib/pgxs/src/makefiles/../../src/Makefile.global:1085: login_hook.bc] Error 1
> make[1]: *** Waiting for unfinished jobs....
> In file included from /usr/pgsql-17/include/server/postgres.h:46,
>                  from login_hook.c:18:
> login_hook.c: In function ‘_PG_ingcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -fvisibility=hidden -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include  -c -o login_hook.o login_hook.c
/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-format-truncation -O2  -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include -flto=thin -emit-llvm -c -o login_hook.bc login_hook.c
login_hook.c:78:32: error: use of undeclared identifier 'IsBackgroundWorker'
   78 |              MyProcPid, MyDatabaseId, IsBackgroundWorker, isExecutingLogin, version);
      |                                       ^
login_hook.c:106:6: error: use of undeclared identifier 'IsBackgroundWorker'
  106 |         if (IsBackgroundWorker)
      |             ^
2 errors generated.
make[1]: *** [/usr/pgsql-17/lib/pgxs/src/makefiles/../../src/Makefile.global:1085: login_hook.bc] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /usr/pgsql-17/include/server/postgres.h:46,
                 from login_hook.c:18:
login_hook.c: In function ‘_PG_init’:
login_hook.c:78:39: error: ‘IsBackgroundWorker’ undeclared (first use in this function); did you mean ‘BackgroundWorkerLock’?
   78 |              MyProcPid, MyDatabaseId, IsBackgroundWorker, isExecutingLogin, version);
      |                                       ^~~~~~~~~~~~~~~~~~
/usr/pgsql-17/include/server/utils/elog.h:147:25: note: in definition of macro ‘ereport_domain’
  147 |                         __VA_ARGS__, errfinish(__FILE__, __LINE__, __func__); \
      |                         ^~~~~~~~~~~
/usr/pgsql-17/include/server/utils/elog.h:239:9: note: in expansion of macro ‘ereport’
  239 |         ereport(elevel, errmsg_internal(__VA_ARGS__))
      |         ^~~~~~~
login_hook.c:76:9: note: in expansion of macro ‘elog’
   76 |         elog(DEBUG3,
      |         ^~~~
login_hook.c:78:39: note: each undeclared identifier is reported only once for each function it appears in
   78 |              MyProcPid, MyDatabaseId, IsBackgroundWorker, isExecutingLogin, version);
      |                                       ^~~~~~~~~~~~~~~~~~
/usr/pgsql-17/include/server/utils/elog.h:147:25: note: in definition of macro ‘ereport_domain’
  147 |                         __VA_ARGS__, errfinish(__FILE__, __LINE__, __func__); \
      |                         ^~~~~~~~~~~
/usr/pgsql-17/include/server/utils/elog.h:239:9: note: in expansion of macro ‘ereport’
  239 |         ereport(elevel, errmsg_internal(__VA_ARGS__))
      |         ^~~~~~~
login_hook.c:76:9: note: in expansion of macro ‘elog’
   76 |         elog(DEBUG3,
      |         ^~~~
/usr/pgsql-17/include/server/utils/elog.h:147:36: warning: left-hand operand of comma expression has no effect [-Wunused-value]
  147 |                         __VA_ARGS__, errfinish(__FILE__, __LINE__, __func__); \
      |                                    ^
/usr/pgsql-17/include/server/utils/elog.h:164:9: note: in expansion of macro ‘ereport_domain’
  164 |         ereport_domain(elevel, TEXTDOMAIN, __VA_ARGS__)
      |         ^~~~~~~~~~~~~~
/usr/pgsql-17/include/server/utils/elog.h:239:9: note: in expansion of macro ‘ereport’
  239 |         ereport(elevel, errmsg_internal(__VA_ARGS__))
      |         ^~~~~~~
login_hook.c:76:9: note: in expansion of macro ‘elog’
   76 |         elog(DEBUG3,
      |         ^~~~
make[1]: *** [<builtin>: login_hook.o] Error 1
it’:
> login_hook.c:78:39: error: ‘IsBackgroundWorker’ undeclared (first use in this function); did you mean ‘BackgroundWorkerLock’?
>    78 |              MyProcPid, MyDatabaseId, IsBackgroundWorker, isExecutingLogin, version);
>       |                                       ^~~~~~~~~~~~~~~~~~
> /usr/pgsql-17/include/server/utils/elog.h:147:25: note: in definition of macro ‘ereport_domain’
>   147 |                         __VA_ARGS__, errfinish(__FILE__, __LINE__, __func__); \
>       |                         ^~~~~~~~~~~
> /usr/pgsql-17/include/server/utils/elog.h:239:9: note: in expansion of macro ‘ereport’
>   239 |         ereport(elevel, errmsg_internal(__VA_ARGS__))
>       |         ^~~~~~~
> login_hook.c:76:9: note: in expansion of macro ‘elog’
>    76 |         elog(DEBUG3,
>       |         ^~~~
> login_hook.c:78:39: note: each undeclared identifier is reported only once for each function it appears in
>    78 |              MyProcPid, MyDatabaseId, IsBackgroundWorker, isExecutingLogin, version);
>       |                                       ^~~~~~~~~~~~~~~~~~
> /usr/pgsql-17/include/server/utils/elog.h:147:25: note: in definition of macro ‘ereport_domain’
>   147 |                         __VA_ARGS__, errfinish(__FILE__, __LINE__, __func__); \
>       |                         ^~~~~~~~~~~
> /usr/pgsql-17/include/server/utils/elog.h:239:9: note: in expansion of macro ‘ereport’
>   239 |         ereport(elevel, errmsg_internal(__VA_ARGS__))
>       |         ^~~~~~~
> login_hook.c:76:9: note: in expansion of macro ‘elog’
>    76 |         elog(DEBUG3,
>       |         ^~~~
> /usr/pgsql-17/include/server/utils/elog.h:147:36: warning: left-hand operand of comma expression has no effect [-Wunused-value]
>   147 |                         __VA_ARGS__, errfinish(__FILE__, __LINE__, __func__); \
>       |                                    ^
> /usr/pgsql-17/include/server/utils/elog.h:164:9: note: in expansion of macro ‘ereport_domain’
>   164 |         ereport_domain(elevel, TEXTDOMAIN, __VA_ARGS__)
>       |         ^~~~~~~~~~~~~~
> /usr/pgsql-17/include/server/utils/elog.h:239:9: note: in expansion of macro ‘ereport’
>   239 |         ereport(elevel, errmsg_internal(__VA_ARGS__))
>       |         ^~~~~~~
> login_hook.c:76:9: note: in expansion of macro ‘elog’
>    76 |         elog(DEBUG3,
>       |         ^~~~
> make[1]: *** [<builtin>: login_hook.o] Error 1
>

**Comment by M-Butter** [comment]
Wow, you are early. I didn't even realise that Postgres 17 beta1 was out yet.

The plan is to make login_hook still work in Postgres 17 so everyone will have the opportunity to move over to the new login trigger that comes with Postgres 17.  So in postgres 18, the support for the login_hook extension will stop.

I'll start working on it.

Regards,
Martin.

**Comment by M-Butter** [comment]
Please pull the latest version and retry.

**Comment by devrimgunduz** [comment]
Hi,
Regression tests fail. Log is attached.
Thanks! Devrim

[login_hook-pg17-regression-diffs.txt](https://github.com/splendiddata/login_hook/files/15490774/login_hook-pg17-regression-diffs.txt)

**Comment by M-Butter** [comment]
Hello Devrim,
Did you add
`session_preload_libraries = 'login_hook'`
to your postgresql.conf file?
Regards,
Martin.

**Comment by devrimgunduz** [comment]
Hi,

We need a new release so that I can build the RPMs. Can you please do that?

Thanks! Devrim

**Comment by M-Butter** [comment]
Hello Devrim,

I was waiting for the release of Postgres17.0  before tagging it (as some major changes were necessary between Postgres 14beta1 and 14beta2). But the Postgres17 betas look pretty stable, so I'm taking the gamble and will create the tag.

Regards,
Martin.

**Comment by devrimgunduz** [comment]
Thanks @M-Butter !
