### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by mrechte** [splendiddata/login_hook#3]
Hello,

First, thanks for publishing this extension.

We are interested using your extension, however we have a few comments on the source code:

l108: get_database_name() return value may be NULL and is not tested as such.
l121: emptyArgVector is not used, so line may be deleted, including l148.
l133: If error occurs in SPI_execute(), because something is wrong in the login_hook.login SQL function, nobody can log in, including SUPERUSER. Any error should be caught here with an appropriate log message.
l134: this line may be useless.

Regards

**Comment by M-Butter** [comment]
Thanks for your comment and sorry that it took so long before I noticed it. I'm fairly new in github and only saw your issue when I started working on Postgres 13.

@108: I didn't realize that a database without name could even exist.

@121: You are right.

@133: Thanks for your enhancement. I pulled it and added a check that only a superuser can login.

@134: This line makes the login_hook.is_executing_login_hook() return false ever after the first invocation of login_hook.login(). I re-entered the line and added some comment to it,

Regards
