### ISSUE TITLE
Database crashes

### ISSUE THREAD

**Issue by markhooper99** [splendiddata/login_hook#5]
We've installed this into an EDB Postgres AS 12 database on a Centos7 system and the installation/make went fine.
However, upon database startup there are a series of fatal errors - I ended up just stopping the service.
I comment the  session_preload_libraries = 'login_hook' line from postgresql.conf and the database starts up fine.

I've attached the log - all I can see is 'Segmentation fault' errors so there's not much to go on.
Any thoughts?  Thanks.

[edb-2020-11-27_100315.log](https://github.com/splendiddata/login_hook/files/5608787/edb-2020-11-27_100315.log)

**Comment by markhooper99** [comment]
Just a little more information about this...  the problem only starts once I issue the 'create extension login_hook;'

**Comment by M-Butter** [comment]
Thank you for your issue report.
EDB does do some things in a different way as the community version, and is not completely open source. I don't have an EDB database to my disposal, so I'm afraid I cannot be of much help.

I will install PostgreSQL on a Centos7 virtual machine and see if I can reproduce your problem.

**Comment by markhooper99** [comment]
I appreciate your response, thanks.
We’re really hoping that we can find a way to make login_hook work as it would help our environment significantly.


Mark Hooper
Chief Database Architect
Katalyst Data Management
Direct: +1 403 718 6210
Cell: +1 403 650 5218
katalystdm.com<http://www.katalystdm.com/> | seismiczone.com<http://www.seismiczone.com/>

**Comment by M-Butter** [comment]
The login_hook database extension appears to work perfectly well in the PostgreSQL12.5 community version under Centos7. So I'm afraid you'll have to ask EDB to help you.

**Comment by markhooper99** [comment]
I've been in contact with EDB and they are willing to provide you a copy of EDB Postgres Advanced Server and even work with you to get login_hook working in their database.  Sound like a plan ?
